[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Dashboards = "9024f26f-ba4d-4e0a-965a-ad5b1da667aa"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
